#!/bin/bash

myname=${0##*/}
# shellcheck disable=SC1091
source "scripts/utils"
# shellcheck disable=SC1091
source "scripts/kern"

RUST_INSTALL_URL="https://sh.rustup.rs"
NEPER_INSTALL_URL="https://github.com/BobAnkh/neper.git"
PAHOLE_INSTALL_URL="https://git.kernel.org/pub/scm/devel/pahole/pahole.git"
LLVM_INSTALL_URL="https://github.com/llvm/llvm-project.git"
MAHIMAHI_INSTALL_URL="https://github.com/BobAnkh/mahimahi-prune.git"
ANTELOPE_INSTALL_URL="https://github.com/wql2002/antelope.git"

install_rust() {
    echo '[INSTALL][RUST] Installing rust...'
    echo "[INSTALL][RUST] Rustc check..."
    if command -v rustc >/dev/null 2>&1; then
        echo '[INSTALL][RUST] Exists rustc...skip intstall!'
    else
        echo '[INSTALL][RUST] No exists rustc...install rust!'
        sudo apt install curl -y
        curl --proto '=https' --tlsv1.2 -sSf "$RUST_INSTALL_URL" | sh -s -- -y
        # shellcheck disable=SC1091
        source "$HOME"/.cargo/env
        echo "[INSTALL][RUST] Install rust done!"
    fi
}

install_neper() {
    echo '[INSTALL][NEPER] Installing neper...'
    cd /home/vagrant/tools && git_clone "$NEPER_INSTALL_URL" neper
    cd /home/vagrant/tools/neper && make
    sudo make install
    echo "[INSTALL][NEPER] Install neper done!"
}

install_pahole() {
    echo '[INSTALL][PAHOLE] Installing pahole...'
    sudo apt update -y && sudo apt install clang libdw-dev libdw1 libdwarf1 libdwarf-dev cmake -y
    cd /home/vagrant/kern_src && git_clone --depth=1 "$PAHOLE_INSTALL_URL" pahole && cd pahole || exit 1
    mk_folder build && cd build && cmake -D__LIB=lib ..
    sudo make install
    sudo ldconfig /usr/local/lib
    if ! pahole --version; then
        echo '[INSTALL][PAHOLE] Install pahole failed!'
        exit 1
    fi
    echo "[INSTALL][PAHOLE] Install pahole done!"
}

update_llvm_alternative() {
    if [ $# -ne 2 ]; then
        echo Usage: update_llvm_alternative version priority
        exit 1
    fi

    version=${1}
    priority=${2}
    path="/usr/bin/"

    master="llvm-config"
    slaves="llvm-addr2line llvm-ar llvm-as llvm-bcanalyzer llvm-bitcode-strip llvm-cat llvm-cfi-verify llvm-cov llvm-c-test llvm-cvtres llvm-cxxdump llvm-cxxfilt llvm-cxxmap llvm-debuginfod llvm-debuginfod-find llvm-diff llvm-dis llvm-dlltool llvm-dwarfdump llvm-dwarfutil llvm-dwp llvm-exegesis llvm-extract llvm-gsymutil llvm-ifs llvm-install-name-tool llvm-jitlink llvm-jitlink-executor llvm-lib llvm-libtool-darwin llvm-link llvm-lipo llvm-lto llvm-lto2 llvm-mc llvm-mca llvm-ml llvm-modextract llvm-mt llvm-nm llvm-objcopy llvm-objdump llvm-omp-device-info llvm-opt-report llvm-otool llvm-pdbutil llvm-PerfectShuffle llvm-profdata llvm-profgen llvm-ranlib llvm-rc llvm-readelf llvm-readobj llvm-reduce llvm-remark-size-diff llvm-rtdyld llvm-sim llvm-size llvm-split llvm-stress llvm-strings llvm-strip llvm-symbolizer llvm-tapi-diff llvm-tblgen llvm-tli-checker llvm-undname llvm-windres llvm-xray"

    update_alternatives "${version}" "${priority}" "${master}" "${slaves}" "${path}"

    master="clang"
    slaves="analyze-build asan_symbolize bugpoint c-index-test clang++ clang-apply-replacements clang-change-namespace clang-check clang-cl clang-cpp clangd clang-doc clang-extdef-mapping clang-format clang-format-diff clang-include-fixer clang-linker-wrapper clang-move clang-nvlink-wrapper clang-offload-bundler clang-offload-packager clang-offload-wrapper clang-pseudo clang-query clang-refactor clang-rename clang-reorder-fields clang-repl clang-scan-deps clang-tidy count diagtool dsymutil FileCheck find-all-symbols git-clang-format hmaptool hwasan_symbolize intercept-build ld64.lld ld.lld llc lld lldb lldb-argdumper lldb-instr lldb-server lldb-vscode lld-link lli lli-child-target modularize not obj2yaml opt pp-trace run-clang-tidy sancov sanstats scan-build scan-build-py scan-view split-file UnicodeNameMappingGenerator verify-uselistorder wasm-ld yaml2obj yaml-bench"

    update_alternatives "${version}" "${priority}" "${master}" "${slaves}" "${path}"
}

install_llvm() {
    local llvm_version=${1:-"16"}
    echo "[INSTALL][LLVM] Installing llvm version: $llvm_version..."
    cd /home/vagrant/tools && mk_folder llvm && cd llvm || exit 1
    wget https://apt.llvm.org/llvm.sh
    # shellcheck disable=SC2016
    sed -i 's/add-apt-repository "\${REPO_NAME}"/add-apt-repository -y "\${REPO_NAME}"/' llvm.sh
    chmod +x llvm.sh
    sudo -E ./llvm.sh "$llvm_version"
    sudo apt install llvm clang -y
    update_llvm_alternative "$llvm_version" 10
    echo "[INSTALL][LLVM] Install llvm done!"
}

install_llvm_manual() {
    local generator_arg=${1:-"unix"}
    local generator='Unix Makefiles'
    case $generator_arg in
    ninja)
        generator='Ninja'
        echo "[INSTALL][LLVM] Installing self-compiled llvm with $generator..."
        sudo apt install ninja-build -y
        ;;
    unix)
        generator='Unix Makefiles'
        echo "[INSTALL][LLVM] Installing self-compiled llvm with $generator..."
        ;;
    *)
        echo "[INSTALL][LLVM] Unknown generator $generator_arg"
        exit 1
        ;;
    esac
    sudo apt update -y && sudo apt install clang lld cmake -y
    cd /home/vagrant/tools && git_clone --depth=1 "$LLVM_INSTALL_URL" llvm-project
    cd llvm-project && mk_folder build && cd build || exit
    cmake -G "$generator" -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="X86;BPF" -DCMAKE_BUILD_TYPE="Release" -DLLVM_INCLUDE_TESTS=OFF ../llvm
    cmake --build . -j "$(nproc)"
    sudo cmake --build . --target install
    echo "[INSTALL][LLVM] Install llvm(self-compiled) done!"
}

install_bpftool() {
    local kern_version=${1:-"6.2"}
    echo "[INSTALL][BPFTOOL] Installing bpftool..."
    sudo apt install gcc-multilib libbpf-dev -y
    cd "/home/vagrant/kern_src/linux-${kern_version}/tools/bpf/bpftool" || exit 1
    sudo make && sudo make install
    echo "[INSTALL][BPFTOOL] Install bpftool done!"
}

install_mahimahi() {
    echo '[INSTALL][MAHIMAHI] Installing Mahimahi...'
    sudo apt update -y && sudo apt-get install autotools-dev autoconf libtool libssl-dev xcb libxcb-composite0-dev libxcb-present-dev libcairo2-dev libpango1.0-dev dnsmasq -y
    sudo sysctl -w net.ipv4.ip_forward=1
    cd /home/vagrant/tools && git_clone "$MAHIMAHI_INSTALL_URL" mahimahi
    cd /home/vagrant/tools/mahimahi || exit 1
    ./autogen.sh && ./configure && make
    sudo make install
    echo "[INSTALL][MAHIMAHI] Install pruned mahimahi done!"
}

install_depot() {
    echo '[INSTALL][DEPOT] Installing depot_tools...'
    cd /home/vagrant/tools && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    # shellcheck disable=SC2016
    echo 'export PATH=/home/vagrant/tools/depot_tools:$PATH' >>/home/vagrant/.bashrc
}

install_antelope() {
    local kern_version=${1:-"6.2"}
    echo '[INSTALL][ANTELOPE] Installing Antelope...'
    cd /home/vagrant || exit 1
    git clone "$ANTELOPE_INSTALL_URL" antelope && cd antelope || exit 1
    echo "[INSTALL][ANTELOPE] Unzip models..."
    tar -xvf models.tar.xz
    sudo apt update -y
    echo '[INSTALL][ANTELOPE] Installing necessary dependencies...'
    sudo apt-get install bpfcc-tools python3-pip gnuplot iperf3 -y
    mkdir ~/venv
    sudo pip3 install -U virtualenv
    virtualenv ~/venv -p python3.7
    source ~/venv/bin/activate
    pip install numpy
    pip install xgboost
    pip install apscheduler
    deactivate

    echo "[INSTALL][ANTELOPE] Compile .so shared file"
    # cd /home/vagrant/antelope
    # gcc -shared -o transfer_cc.so -fPIC transfer_cc.c
    echo "[INSTALL][ANTELOPE] Compile _kern.o file"
    # cd "/home/vagrant/kern_src/linux-${kern_version}"
    # cp /home/vagrant/antelope/tcp_changecc_kern.c "samples/bpf/tcp_changecc_kern.c"
    # MAKEFILE_PATH="samples/bpf/Makefile"
    # LINE_NUMBER=175
    # sed -i "${LINE_NUMBER}i always-y += tcp_changecc_kern.o" "${MAKEFILE_PATH}"
    # make M=samples/bpf
    # cp "samples/bpf/tcp_changecc_kern.o" "/home/vagrant/antelope/tcp_changecc_kern.o"
    cd /home/vagrant/antelope
    echo "[INSTALL][ANTELOPE] antelope installation succeeds"
}

install_kern() {
    local kern_type=${1:-"customize"}
    if [ $# -gt 0 ]; then
        shift
    fi
    case $kern_type in
    mainline)
        install_mainline_kern "$@"
        ;;
    customize | *)
        install_customize_kern "$@"
        ;;
    esac
}

usage() {
    cat >&2 <<EOL
Install tools related to this project.
Usage:
$myname options tools ...

options:
	--help|-h                   Print this help message
    --kern-version              Specify kernel version to be installed [default: 6.2]
    --customize-kern-config     Customize kernel configuration [ubuntu, current, default]

tools:
    mahimahi                    Install a pruned version of network emulation tool mahimahi
    kern                        Install customized kernel from source
    mainline                    Install mainline kernel with toolkit from ubuntu ppa
    rust                        Install rust toolchain
    pahole                      Install pahole for enabling btf
    llvm                        Install llvm for compling bpf programs
    bpftool                     Install bpftool for debugging bpf programs
    depot                       Install depot to download chromium source code for alphartc

    tools can be repeted to install multiple tools

Example:
    $myname --customize-kern-config  mahimahi kern
EOL
    exit 1
}

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
    --help | -h)
        usage
        exit 1
        ;;
    --kern-version | -m)
        KERN_VERSION=$2
        shift # past argument
        shift # past value
        ;;
    --customize-kern-config | -c)
        CUSTOMIZE_KERN_CONFIG=$2
        shift # past argument
        shift # past value
        ;;
    --* | -*)
        echo "Unknown option $1"
        usage
        exit 1
        ;;
    *)
        POSITIONAL_ARGS+=("$1") # save positional arg
        shift                   # past argument
        ;;
    esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

for arg in "$@"; do
    case $arg in
    mahimahi)
        install_mahimahi
        ;;
    kern)
        install_kern "customize" "$CUSTOMIZE_KERN_CONFIG" "$KERN_VERSION"
        ;;
    mainline)
        install_kern "mainline" "$KERN_VERSION"
        ;;
    rust)
        install_rust
        ;;
    pahole)
        install_pahole
        ;;
    llvm)
        install_llvm 16
        ;;
    llvm-alternative)
        update_llvm_alternative "$llvm_version" 10
        ;;
    llvm-manual)
        install_llvm_manual ninja
        ;;
    bpftool)
        install_bpftool "$KERN_VERSION"
        ;;
    depot)
        install_depot
        ;;
    antelope)
        install_antelope "$KERN_VERSION"
        ;;
    esac
done
